### ISSUE TITLE
ERROR: Mail from must equal authorized user

### ISSUE THREAD

**Issue by hick** [splitbrain/dokuwiki-plugin-smtp#16]
It may be different for different smtp server.  

the problem is that the "MAIL FROM" is empty

![image](https://cloud.githubusercontent.com/assets/38886/20454832/eb433a0c-ae85-11e6-8854-b7440399fe87.png)

one way to fix is as following(sorry for not familiar with PR):

![image](https://cloud.githubusercontent.com/assets/38886/20454842/37db1b8c-ae86-11e6-8031-913ef4ffd42f.png)

**Comment by splitbrain** [comment]
As the documentation states, you have to set the mailfrom config setting.
