### ISSUE TITLE
Sender address rejected

### ISSUE THREAD

**Issue by tsunamaru** [splitbrain/dokuwiki-plugin-smtp#38]
Dokuwiki Release 2018-04-22c "Greebo"
nginx 1.18.0
PHP 7.3.17

SMTP settings:
<p align="center"><p>
<img src="https://imgur.com/download/eqcCjLc/" width="100%" alt="Loading..."/>
</p>

```
There was an unexpected problem communicating with SMTP: Unexpected return code -
Expected: 250, Got: 553 | 553 5.7.1 Sender address rejected: not owned by auth user. 
```
```
Set: the server
Set: the auth
Set: a message will be sent
Connecting to smtp.yandex.ru at 465
Got: 220 vla1-ee05250d997a.qloud-c.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)
Sent: EHLO [redacted]
Got: 250-vla1-ee05250d997a.qloud-c.yandex.net
Got: 250-8BITMIME
Got: 250-PIPELINING
Got: 250-SIZE 42991616
Got: 250-AUTH LOGIN PLAIN XOAUTH2
Got: 250-DSN
Got: 250 ENHANCEDSTATUSCODES
Sent: AUTH LOGIN
Got: 334 [redacted]
Sent: [redacted]
Got: 334 [redacted]
Sent: [redacted]
Got: 235 2.7.0 Authentication successful.
Sent: MAIL FROM:<>
Got: 553 5.7.1 Sender address rejected: not owned by auth user.
```

What I'm doing wrong?

**Comment by tsunamaru** [comment]
I did a very dirty hack, edited [this line](https://github.com/splitbrain/dokuwiki-plugin-smtp/blob/777cc753669895fe60e583c0ed41a094a0188377/subtree/txtthinking/Mailer/src/Mailer/SMTP.php#L266) directly on my server:
`$in = "MAIL FROM:<noreply@[redacted]>" . $this->CRLF;`

And after this...
<img src="https://imgur.com/download/XbAZPv2/" width="100%" alt="Loading..."/>

**Comment by splitbrain** [comment]
read the documentation. you need to set the mailfrom config.
