### ISSUE TITLE
Not able to test Mail Functionality

### ISSUE THREAD

**Issue by suhasravva** [splitbrain/dokuwiki-plugin-smtp#4]
I used Gmail server
smtp.gmail.com
port : 587
SMTP : TLS
Username: username@gmail.com( i specified my email)
password: gave here

Even i tried with SSL security. But not working and throws below log on the screen. Please, could you help me in resolving this.
SMTP log:
Set: the server
Set: the auth
Set: a message will be sent
Connecting to smtp.gmail.com at 587
Got: 220 smtp.gmail.com ESMTP fp5sm3863745pbb.94 - gsmtp
Sent: EHLO localhost.localdomain
Got: 250-smtp.gmail.com at your service, [121.241.48.5]
Got: 250-SIZE 35882577
Got: 250-8BITMIME
Got: 250-STARTTLS
Got: 250-ENHANCEDSTATUSCODES
Got: 250-PIPELINING
Got: 250-CHUNKING
Got: 250 SMTPUTF8
Sent: STARTTLS
Got: 220 2.0.0 Ready to start TLS
Sent: EHLO localhost.localdomain
Got: 250-smtp.gmail.com at your service, [121.241.48.5]
Got: 250-SIZE 35882577
Got: 250-8BITMIME
Got: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH
Got: 250-ENHANCEDSTATUSCODES
Got: 250-PIPELINING
Got: 250-CHUNKING
Got: 250 SMTPUTF8
Sent: AUTH LOGIN
Got: 334 VXNlcm5hbWU6
Sent: c3VoYXNiZWNvb2xAZ21haWwuY29t
Got: 334 UGFzc3dvcmQ6
Sent: Y2xhc3N1cGRhdGVz
Got: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsdj
Got: 534-5.7.14 B4710C_pC6z1SAgnZlu7Gk3TY7X0dvt7CluaK_xHcdbl8T8BjiLdgLw7MYj6ej9Hp9uhan
Got: 534-5.7.14 HoSfFlEKxkTHxPosam_lZkkYE2kvUGwcXrztDVbHaV6cV9bddjVZW8pYJs1CCbtvI0FeyI
Got: 534-5.7.14 AdnB6Ify9bAlA6UOvz3xVfwcIZbuWnabo98ehJjjWt88ykhtXYa_1H0JYOMtjPgLeV_ICC
Got: 534-5.7.14 iUR0OW_zW9kPcjtdioo0-1JjZOIU> Please log in via your web browser and
Got: 534-5.7.14 then try again.
Got: 534-5.7.14  Learn more at
Got: 534 5.7.14  https://support.google.com/mail/answer/78754 fp5sm3863745pbb.94 - gsmtp

**Comment by splitbrain** [comment]
See https://support.google.com/mail/answer/78754
