### ISSUE TITLE
SMTP fails for ipv6 address

### ISSUE THREAD

**Issue by mvscheven** [splitbrain/dokuwiki-plugin-smtp#41]
Presumably after the last update of our dokuwiki some days ago the smtp plugin not longer works as before.Sending mails fails with the following message:

> There was an unexpected problem communicating with SMTP: Unexpected return code - Expected: 250, Got: 501 | 501 5.5.2 <[2001:7c0:2041:8::19]>: Helo command rejected: invalid ip address

Here is the full log:

Set: the server
Set: a message will be sent
Connecting to mailrelay.uni-stuttgart.de at 25
Got: 220 mx1.rus.uni-stuttgart.de ESMTP Postfix
Sent: EHLO [2001:7c0:2041:8::19]
Got: 250-mx1.rus.uni-stuttgart.de
Got: 250-PIPELINING
Got: 250-SIZE 31457280
Got: 250-ETRN
Got: 250-STARTTLS
Got: 250-ENHANCEDSTATUSCODES
Got: 250-8BITMIME
Got: 250 DSN
Sent: STARTTLS
Got: 220 2.0.0 Ready to start TLS
Sent: EHLO [2001:7c0:2041:8::19]
Got: 250-mx1.rus.uni-stuttgart.de
Got: 250-PIPELINING
Got: 250-SIZE 31457280
Got: 250-ETRN
Got: 250-AUTH PLAIN LOGIN
Got: 250-ENHANCEDSTATUSCODES
Got: 250-8BITMIME
Got: 250 DSN
Sent: MAIL FROM:<mvs@ibb.uni-stuttgart.de>
Got: 250 2.1.0 Ok
Sent: RCPT TO:<mvs@ibb.uni-stuttgart.de>
Got: 501 5.5.2 <[2001:7c0:2041:8::19]>: Helo command rejected: invalid ip address

According to our mail admin postfix expects a prefix for ipv6 addresses, like: `Sent: EHLO [ipv6:2001:7c0:2041:8::19]`

Have you experienced a similar problem before? Do you have any suggestions how to further debug or solve the problem?
Thank you for any advice!
Malte

**Comment by splitbrain** [comment]
You can explicitly set the host name used during EHLO using the `localdomain` setting. Ideally it should be a valid FQDN not an IP address.

**Comment by mvscheven** [comment]
Thank you for this immediate answer.

Setting `localdomain` solved my problem, even though it worked many years without and nothing was changed since.
