### ISSUE TITLE
SMTP plugin does not save auth_pass setting

### ISSUE THREAD

**Issue by RJLodigiani** [splitbrain/dokuwiki-plugin-smtp#62]
SMTP plugin

There was an unexpected problem communicating with SMTP: Unexpected return code - Expected: 334, Got: 535 | 535 Incorrect authentication data.

Does not save auth_pass setting.

O/S			Windows 11
Browser		Chrome

Server
Host		        az1-ss44.a2hosting.com
Outgoing email	(SMTP/SMTP-SSL)
PHP version	        7.4
Apache		        2.4.57

Dokuwiki Version	Release 2023-04-04a "Jack Jackrum"		6/SET/2023
+ HTMLOK because site has legacy HTML code.

SMTP plugin configuration
Version/Date 	        2023-04-04 "Jack Jackrum" 
smpt_host		az1-ss44.a2hosting.com
smpt_port		465
smpt_ssl		        SSL
smpt_auth_user	{ mail@***.org }
smpt_auth_pass	{  *** }

Notification Settings configuration
    mailfrom		 { mail@***.org } same as smpt_auth_user.

**Comment by splitbrain** [comment]
cannot reproduce. Your log output shows that a password is used.
